### ISSUE TITLE
ライセンスが不明

### ISSUE THREAD

**Issue by fand** [tiwanari/emoticon#13]
こちらで提供されている辞書を利用したCLIツールを作ったのですが、ライセンスはMITでよろしいでしょうか？ (๑´╹‸╹`๑)
https://github.com/fand/kao

**Comment by tiwanari** [comment]
@fand ご連絡ありがとございます！全く考えてもなかったですが、MITとさせていただけたらと思います
追加しておきました
https://github.com/tiwanari/emoticon/commit/4a5fe5e21fe72874ea72df3dcccb852d22d08f80

**Comment by fand** [comment]
ありがとうございます！！٩( ᐛ )و

**Comment by tiwanari** [comment]
あと readme にツールへのリンクも貼らせていただきました！(´◔౪◔)۶ﾖｯｼｬ!

**Comment by tiwanari** [comment]
閉じますね〜
