### ISSUE TITLE
エクスポート

### ISSUE THREAD

**Issue by tiwanari** [tiwanari/emoticon#5]
エクスポートがばらばらで，diffが役に立たない

**Comment by keihayashi** [comment]
エクスポートがばらばら、とはどゆこと…？辞書からのエクスポートのことを言っているよね？それがgit diffとどう関係するの？(•〰•๑)

**Comment by tiwanari** [comment]
辞書をエクスポートすることできて、それが今の emoticon.txt と同じなんだけど、新しく加えると顔文字の順番が変わってる気がしたというのが問題で、
順番がバラバラだと diff みたときにどれが新しいものか、よくわからんくなるなあって
そしてまさに #11 で解決できると思うぞい！

**Comment by keihayashi** [comment]
ああ　そういうことか　#11 明日でよければ私スクリプトかくよ⁽⁽◝( ˙ ꒳ ˙ )◜⁾⁾

**Comment by tiwanari** [comment]
(´◔౪◔)۶ﾖｯｼｬ!
